export const FAILURE_AXES = [
  {
    id: "f1",
    axisFa: "قطعه پمپ نرسید",
    triggerFa: "روز ۸ بدون ورود گمرک",
    impactFa: "بازگشت به تأخیر پایه + هزینه نیمه‌کاره",
    earlyWarningFa: "وضعیت PO و ترخیص روزانه",
    contingencyFa: "فعال‌سازی فوری برون‌سپاری اصفهان",
  },
  {
    id: "f2",
    axisFa: "پیمانکار کیفیت را رد می‌کند",
    triggerFa: "تست خلاء زیر حد IEC",
    impactFa: "بازگشت استاتور + ۲۰ روز اضافه",
    earlyWarningFa: "شاهد مهندسی در سیکل اول",
    contingencyFa: "توقف حمل تا پروتکل امضا شود",
  },
  {
    id: "f3",
    axisFa: "قطع برق شیفت شب",
    triggerFa: "اطلاع توانیر / دیسپاچینگ",
    impactFa: "از دست رفتن فشرده‌سازی Overtime",
    earlyWarningFa: "برنامه خاموشی ۴۸ساعته",
    contingencyFa: "دیزل یا لغو سه‌شیفت",
  },
  {
    id: "f4",
    axisFa: "شوک ارز ۳۰٪+",
    triggerFa: "نرخ حواله",
    impactFa: "هزینه قطعه و رزین خارج از مدل",
    earlyWarningFa: "نرخ روزانه خزانه گروه",
    contingencyFa: "سقف تعهد ارزی / رزین موجودی",
  },
  {
    id: "f5",
    axisFa: "کارفرمای MGS58 جریمه می‌گیرد",
    triggerFa: "نامه تأخیر",
    impactFa: "جریمه دوم روی پرتفوی",
    earlyWarningFa: "جلسه هفتگی امور قراردادها",
    contingencyFa: "مذاکره شناوری ۱۰ روزه",
  },
  {
    id: "f6",
    axisFa: "رزین کلاس H کافی نیست",
    triggerFa: "موجودی < safety",
    impactFa: "VPI حتی پس از تعمیر متوقف",
    earlyWarningFa: "RESB vs MARC روزانه",
    contingencyFa: "تخصیص رزین فقط به واحد ۲",
  },
  {
    id: "f7",
    axisFa: "خرابی ثانویه کوره پخت",
    triggerFa: "دمای کوره خارج از باند",
    impactFa: "گلوگاه از VPI به CUR منتقل",
    earlyWarningFa: "نگهداری پیشگیرانه",
    contingencyFa: "کوره پیمانکار با محدودیت انرژی",
  },
  {
    id: "f8",
    axisFa: "حمل فوق‌سنگین مجوز نگرفت",
    triggerFa: "پلیس‌راه / وزن",
    impactFa: "برون‌سپاری غیرقابل اجرا",
    earlyWarningFa: "چک‌لیست لجستیک روز ۰",
    contingencyFa: "بازگشت به تعمیر",
  },
  {
    id: "f9",
    axisFa: "وصول FAT بیش از ۱۲۰ روز",
    triggerFa: "عدم تأیید صورت‌وضعیت",
    impactFa: "کسری سرمایه در گردش",
    earlyWarningFa: "سنجه خزانه هفتگی",
    contingencyFa: "توقف هزینه‌های غیرضروری اقدام",
  },
  {
    id: "f10",
    axisFa: "اینترنت/سامانه بانکی قطع",
    triggerFa: "عدم گشایش پرداخت پیمانکار",
    impactFa: "اقدام نقدی متوقف",
    earlyWarningFa: "پرداخت پیش‌دستانه ریالی",
    contingencyFa: "موتور تصمیم آفلاین — بدون LLM",
  },
];
