/**
 * Canonical extract for MAPNA Pars Generator — Fardis plant.
 *
 * FACT (company): MAPNA Generator Engineering and Manufacturing Co. (PARS),
 * established 1998, plant in Fardis, Alborz; products include MGS58 250 MVA,
 * MGH60 300 MVA hydro, MGS72-SH2 376 MW hydrogen-cooled Class F (unveiled 2025).
 * Sources: mapnagroup.com, mapnagenerator.com, retrieved 2026-09-05.
 *
 * ASSUMPTION: project IDs, order numbers, dates, costs, and cash figures are a
 * structurally realistic synthetic extract for the MVP. They MUST be replaced
 * with SAP S/4HANA extract in the pilot (VALIDATION REQUIRED).
 */

import type {
  CashEvent,
  Commitment,
  Material,
  Milestone,
  Operation,
  ProductionOrder,
  Project,
  Provenance,
  Resource,
  Supplier,
  Wbs,
} from "./types";

const sap = (id: string, extra?: Partial<Provenance>): Provenance => ({
  sourceSystem: "SAP S/4HANA (synthetic extract)",
  sourceRecordId: id,
  sourceKind: "sap",
  confidence: "medium",
  asOf: "2026-09-05",
  ...extra,
});

const assumed = (note: string): Provenance => ({
  sourceSystem: "Mission Control seed",
  sourceKind: "assumption",
  confidence: "assumed",
  asOf: "2026-09-05",
  note,
});

export const PLANT = {
  id: "PLT-1100",
  werks: "1100",
  nameFa: "کارخانه فردیس — شرکت مهندسی و ساخت ژنراتور مپنا (پارس)",
  nameEn: "Fardis Plant — MAPNA Pars Generator",
  city: "فردیس، البرز",
};

export const RESOURCES: Resource[] = [
  {
    id: "WC-VPI-01",
    code: "VPI-01",
    nameFa: "مخزن اشباع خلاء-فشار اصلی",
    nameEn: "Main VPI tank",
    kind: "machine",
    plantId: PLANT.id,
    capacityPerDay: 1,
    capacityUnit: "batch",
    calendarId: "CAL-6D",
    available: false,
    failureProbability: 0.08,
    hourlyCostIrr: 42_000_000,
    energyKwhPerHour: 380,
    alternativeIds: ["WC-VPI-02"],
    laborDependency: ["SK-VPI-OP"],
    materialDependency: ["MAT-RESIN-VPI"],
    supplierDependency: ["SUP-VAC-PUMP"],
    uniqueInPlant: true,
    sapWorkCenter: "VPI01",
    provenance: sap("CRHD/VPI01"),
  },
  {
    id: "WC-VPI-02",
    code: "VPI-02",
    nameFa: "مخزن VPI کوچک (شینه و کویل)",
    nameEn: "Small VPI tank",
    kind: "machine",
    plantId: PLANT.id,
    capacityPerDay: 1,
    capacityUnit: "batch",
    calendarId: "CAL-6D",
    available: true,
    failureProbability: 0.05,
    hourlyCostIrr: 18_000_000,
    energyKwhPerHour: 140,
    alternativeIds: [],
    laborDependency: ["SK-VPI-OP"],
    materialDependency: ["MAT-RESIN-VPI"],
    supplierDependency: ["SUP-VAC-PUMP"],
    uniqueInPlant: false,
    sapWorkCenter: "VPI02",
    provenance: sap("CRHD/VPI02"),
  },
  {
    id: "WC-ROT-01",
    code: "ROT-01",
    nameFa: "تراش CNC روتور WZM-۵۰۰",
    nameEn: "Rotor CNC lathe",
    kind: "machine",
    plantId: PLANT.id,
    capacityPerDay: 16,
    capacityUnit: "hour",
    calendarId: "CAL-6D",
    available: true,
    failureProbability: 0.06,
    hourlyCostIrr: 85_000_000,
    energyKwhPerHour: 220,
    alternativeIds: [],
    laborDependency: ["SK-CNC"],
    materialDependency: [],
    supplierDependency: [],
    uniqueInPlant: true,
    sapWorkCenter: "ROT01",
    provenance: sap("CRHD/ROT01"),
  },
  {
    id: "WC-STK-01",
    code: "STK-01",
    nameFa: "پرس و چیدمان هسته استاتور",
    nameEn: "Stator core stacking press",
    kind: "work_center",
    plantId: PLANT.id,
    capacityPerDay: 18,
    capacityUnit: "hour",
    calendarId: "CAL-6D",
    available: true,
    failureProbability: 0.04,
    hourlyCostIrr: 22_000_000,
    energyKwhPerHour: 90,
    alternativeIds: [],
    laborDependency: [],
    materialDependency: ["MAT-STEEL-LAM"],
    supplierDependency: [],
    uniqueInPlant: false,
    sapWorkCenter: "STK01",
    provenance: sap("CRHD/STK01"),
  },
  {
    id: "WC-WIN-01",
    code: "WIN-01",
    nameFa: "ایستگاه جاگذاری شینه استاتور",
    nameEn: "Stator bar insertion",
    kind: "work_center",
    plantId: PLANT.id,
    capacityPerDay: 16,
    capacityUnit: "hour",
    calendarId: "CAL-6D",
    available: true,
    failureProbability: 0.03,
    hourlyCostIrr: 19_000_000,
    energyKwhPerHour: 25,
    alternativeIds: [],
    laborDependency: ["SK-WIND"],
    materialDependency: ["MAT-CU-BAR"],
    supplierDependency: [],
    uniqueInPlant: false,
    sapWorkCenter: "WIN01",
    provenance: sap("CRHD/WIN01"),
  },
  {
    id: "WC-BAR-01",
    code: "BAR-01",
    nameFa: "ساخت و عایق شینه استاتور",
    nameEn: "Stator bar manufacturing",
    kind: "work_center",
    plantId: PLANT.id,
    capacityPerDay: 20,
    capacityUnit: "hour",
    calendarId: "CAL-6D",
    available: true,
    failureProbability: 0.04,
    hourlyCostIrr: 16_000_000,
    energyKwhPerHour: 40,
    alternativeIds: [],
    laborDependency: [],
    materialDependency: ["MAT-CU-BAR", "MAT-MICA"],
    supplierDependency: [],
    uniqueInPlant: false,
    sapWorkCenter: "BAR01",
    provenance: sap("CRHD/BAR01"),
  },
  {
    id: "WC-CUR-01",
    code: "CUR-01",
    nameFa: "کوره پخت رزین",
    nameEn: "Curing oven",
    kind: "machine",
    plantId: PLANT.id,
    capacityPerDay: 1,
    capacityUnit: "batch",
    calendarId: "CAL-6D",
    available: true,
    failureProbability: 0.05,
    hourlyCostIrr: 28_000_000,
    energyKwhPerHour: 520,
    alternativeIds: [],
    laborDependency: [],
    materialDependency: [],
    supplierDependency: [],
    uniqueInPlant: false,
    sapWorkCenter: "CUR01",
    provenance: sap("CRHD/CUR01"),
  },
  {
    id: "WC-BAL-01",
    code: "BAL-01",
    nameFa: "بالانس دینامیکی روتور",
    nameEn: "Rotor balancing",
    kind: "machine",
    plantId: PLANT.id,
    capacityPerDay: 12,
    capacityUnit: "hour",
    calendarId: "CAL-6D",
    available: true,
    failureProbability: 0.04,
    hourlyCostIrr: 31_000_000,
    energyKwhPerHour: 70,
    alternativeIds: [],
    laborDependency: [],
    materialDependency: [],
    supplierDependency: [],
    uniqueInPlant: true,
    sapWorkCenter: "BAL01",
    provenance: sap("CRHD/BAL01"),
  },
  {
    id: "WC-TST-01",
    code: "TST-01",
    nameFa: "ایستگاه تست الکتریکی و آب‌بندی هیدروژن",
    nameEn: "Electrical & H2 seal test stand",
    kind: "machine",
    plantId: PLANT.id,
    capacityPerDay: 16,
    capacityUnit: "hour",
    calendarId: "CAL-6D",
    available: true,
    failureProbability: 0.03,
    hourlyCostIrr: 36_000_000,
    energyKwhPerHour: 110,
    alternativeIds: [],
    laborDependency: ["SK-TEST"],
    materialDependency: ["MAT-H2-SEAL"],
    supplierDependency: [],
    uniqueInPlant: true,
    sapWorkCenter: "TST01",
    provenance: sap("CRHD/TST01"),
  },
  {
    id: "WC-ASM-01",
    code: "ASM-01",
    nameFa: "مونتاژ نهایی ژنراتور",
    nameEn: "Final assembly",
    kind: "work_center",
    plantId: PLANT.id,
    capacityPerDay: 18,
    capacityUnit: "hour",
    calendarId: "CAL-6D",
    available: true,
    failureProbability: 0.02,
    hourlyCostIrr: 14_000_000,
    energyKwhPerHour: 40,
    alternativeIds: [],
    laborDependency: [],
    materialDependency: [],
    supplierDependency: [],
    uniqueInPlant: false,
    sapWorkCenter: "ASM01",
    provenance: sap("CRHD/ASM01"),
  },
  {
    id: "ENG-ELEC",
    code: "ENG-EL",
    nameFa: "ظرفیت مهندسی الکتریک و عایق",
    nameEn: "Electrical / insulation engineering",
    kind: "engineering",
    plantId: PLANT.id,
    capacityPerDay: 48,
    capacityUnit: "person-hour",
    calendarId: "CAL-6D",
    available: true,
    failureProbability: 0.02,
    hourlyCostIrr: 8_500_000,
    energyKwhPerHour: 0,
    alternativeIds: [],
    laborDependency: [],
    materialDependency: [],
    supplierDependency: [],
    uniqueInPlant: false,
    sapWorkCenter: "ENGEL",
    provenance: sap("CRHD/ENGEL"),
  },
  {
    id: "CASH-WC",
    code: "CASH",
    nameFa: "نقدینگی عملیاتی پارس",
    nameEn: "Operating cash",
    kind: "cash",
    plantId: PLANT.id,
    capacityPerDay: 0,
    capacityUnit: "IRR",
    calendarId: "CAL-FIN",
    available: true,
    failureProbability: 0,
    hourlyCostIrr: 0,
    energyKwhPerHour: 0,
    alternativeIds: [],
    laborDependency: [],
    materialDependency: [],
    supplierDependency: [],
    uniqueInPlant: true,
    provenance: {
      sourceSystem: "Treasury workbook + SAP FSCM (synthetic)",
      sourceKind: "estimated",
      confidence: "low",
      asOf: "2026-09-05",
      note: "Cash is not taken from SAP GL opening balance in MVP. VALIDATION REQUIRED.",
    },
  },
];

export const SUPPLIERS: Supplier[] = [
  {
    id: "SUP-RESIN-EU",
    code: "V-4410",
    nameFa: "تأمین‌کننده رزین اپوکسی (کانال واسطه اروپا)",
    nameEn: "Epoxy resin (EU intermediary)",
    country: "EU / UAE channel",
    sanctionedChannel: true,
    reliability: 0.62,
    typicalDelayDays: 28,
    provenance: sap("LFA1/V4410"),
  },
  {
    id: "SUP-VAC-PUMP",
    code: "V-8821",
    nameFa: "قطعات پمپ خلاء VPI",
    nameEn: "VPI vacuum pump spares",
    country: "DE via intermediary",
    sanctionedChannel: true,
    reliability: 0.55,
    typicalDelayDays: 35,
    provenance: sap("LFA1/V8821"),
  },
  {
    id: "SUP-FORGE",
    code: "V-1102",
    nameFa: "آهنگری شفت روتور (داخلی)",
    nameEn: "Rotor shaft forge (domestic)",
    country: "IR",
    sanctionedChannel: false,
    reliability: 0.78,
    typicalDelayDays: 12,
    provenance: sap("LFA1/V1102"),
  },
  {
    id: "SUP-VPI-ISO",
    code: "V-3308",
    nameFa: "کارگاه اشباع صنعتی اصفهان (پیمانکار)",
    nameEn: "Isfahan industrial VPI contractor",
    country: "IR",
    sanctionedChannel: false,
    reliability: 0.7,
    typicalDelayDays: 8,
    provenance: assumed("پیمانکار خارج از SAP MM — منبع خارجی"),
  },
];

export const MATERIALS: Material[] = [
  {
    id: "MAT-RESIN-VPI",
    code: "R-EPX-H2",
    nameFa: "رزین اپوکسی کلاس H مخصوص VPI ژنراتور هیدروژن‌خنک",
    nameEn: "Class H VPI epoxy resin",
    plantId: PLANT.id,
    uom: "KG",
    onHand: 420,
    reserved: 380,
    safetyStock: 250,
    leadTimeDays: 52,
    importDependent: true,
    fxSensitive: true,
    unitCostIrr: 48_000_000,
    supplierId: "SUP-RESIN-EU",
    sapMatnr: "R-EPX-H2",
    provenance: sap("MARC/R-EPX-H2"),
  },
  {
    id: "MAT-CU-BAR",
    code: "CU-BAR-72",
    nameFa: "هادی مسی شینه استاتور MGS72",
    nameEn: "Stator bar copper",
    plantId: PLANT.id,
    uom: "M",
    onHand: 2100,
    reserved: 1600,
    safetyStock: 400,
    leadTimeDays: 21,
    importDependent: false,
    fxSensitive: true,
    unitCostIrr: 12_500_000,
    sapMatnr: "CU-BAR-72",
    provenance: sap("MARC/CU-BAR-72"),
  },
  {
    id: "MAT-STEEL-LAM",
    code: "SI-LAM-50",
    nameFa: "ورق سیلیکون هسته استاتور",
    nameEn: "Silicon steel laminations",
    plantId: PLANT.id,
    uom: "T",
    onHand: 86,
    reserved: 54,
    safetyStock: 20,
    leadTimeDays: 18,
    importDependent: false,
    fxSensitive: false,
    unitCostIrr: 890_000_000,
    sapMatnr: "SI-LAM-50",
    provenance: sap("MARC/SI-LAM-50"),
  },
  {
    id: "MAT-MICA",
    code: "MIC-TB",
    nameFa: "نوار میکا عایق اصلی شینه",
    nameEn: "Mica tape",
    plantId: PLANT.id,
    uom: "M",
    onHand: 5400,
    reserved: 4100,
    safetyStock: 1200,
    leadTimeDays: 40,
    importDependent: true,
    fxSensitive: true,
    unitCostIrr: 2_400_000,
    sapMatnr: "MIC-TB",
    provenance: sap("MARC/MIC-TB"),
  },
  {
    id: "MAT-H2-SEAL",
    code: "H2-SEAL",
    nameFa: "سیستم آب‌بندی هیدروژن و یاتاقان روغنی",
    nameEn: "H2 sealing oil system",
    plantId: PLANT.id,
    uom: "SET",
    onHand: 2,
    reserved: 2,
    safetyStock: 1,
    leadTimeDays: 70,
    importDependent: true,
    fxSensitive: true,
    unitCostIrr: 18_500_000_000,
    sapMatnr: "H2-SEAL",
    provenance: sap("MARC/H2-SEAL"),
  },
];

export const PROJECTS: Project[] = [
  {
    id: "PRJ-H2-376-U2",
    pspid: "H2-376-U2",
    nameFa: "ژنراتور هیدروژن‌خنک MGS72-SH2 واحد ۲",
    nameEn: "MGS72-SH2 376 MW H2-cooled — Unit 2",
    plantId: PLANT.id,
    customer: "کارفرمای سیکل ترکیبی (پروژه گروه مپنا)",
    productModel: "MGS72-SH2 50Hz · 376 MW · Class F",
    status: "REL",
    progressPct: 62,
    plannedStartDay: -308,
    plannedFinishDay: 101,
    contractualFinishDay: 106,
    contractValueIrr: 2_850_000_000_000,
    remainingInvoiceIrr: 855_000_000_000,
    strategic: true,
    penaltyPerDayPct: 0.0015,
    penaltyCapPct: 0.1,
    collectionLagDays: 90,
    provenance: sap("PROJ/H2-376-U2"),
  },
  {
    id: "PRJ-MGS58-CC",
    pspid: "MGS58-CC4",
    nameFa: "ژنراتور هواخنک MGS58 · ۲۵۰ MVA",
    nameEn: "MGS58 250 MVA air-cooled",
    plantId: PLANT.id,
    customer: "نیروگاه سیکل ترکیبی داخلی",
    productModel: "MGS58 250 MVA",
    status: "REL",
    progressPct: 48,
    plannedStartDay: -240,
    plannedFinishDay: 128,
    contractualFinishDay: 140,
    contractValueIrr: 1_420_000_000_000,
    remainingInvoiceIrr: 497_000_000_000,
    strategic: false,
    penaltyPerDayPct: 0.001,
    penaltyCapPct: 0.08,
    collectionLagDays: 75,
    provenance: sap("PROJ/MGS58-CC4"),
  },
  {
    id: "PRJ-MGH60",
    pspid: "MGH60-HY2",
    nameFa: "ژنراتور آبی MGH60 · ۳۰۰ MVA",
    nameEn: "MGH60 300 MVA hydro",
    plantId: PLANT.id,
    customer: "سد و نیروگاه برق‌آبی",
    productModel: "MGH60 300 MVA vertical",
    status: "REL",
    progressPct: 41,
    plannedStartDay: -190,
    plannedFinishDay: 162,
    contractualFinishDay: 180,
    contractValueIrr: 1_680_000_000_000,
    remainingInvoiceIrr: 672_000_000_000,
    strategic: false,
    penaltyPerDayPct: 0.0008,
    penaltyCapPct: 0.08,
    collectionLagDays: 120,
    provenance: sap("PROJ/MGH60-HY2"),
  },
];

export const WBS: Wbs[] = [
  {
    id: "WBS-H2-STATOR",
    posid: "H2-376-U2.ST",
    nameFa: "استاتور و عایق",
    projectId: "PRJ-H2-376-U2",
    plannedFinishDay: 58,
    plannedCostIrr: 620_000_000_000,
    actualCostIrr: 348_000_000_000,
    provenance: sap("PRPS/H2-376-U2.ST"),
  },
  {
    id: "WBS-H2-ROTOR",
    posid: "H2-376-U2.RT",
    nameFa: "روتور",
    projectId: "PRJ-H2-376-U2",
    plannedFinishDay: 72,
    plannedCostIrr: 540_000_000_000,
    actualCostIrr: 301_000_000_000,
    provenance: sap("PRPS/H2-376-U2.RT"),
  },
  {
    id: "WBS-H2-ASM",
    posid: "H2-376-U2.AS",
    nameFa: "مونتاژ، تست و تحویل",
    projectId: "PRJ-H2-376-U2",
    plannedFinishDay: 101,
    plannedCostIrr: 210_000_000_000,
    actualCostIrr: 44_000_000_000,
    provenance: sap("PRPS/H2-376-U2.AS"),
  },
  {
    id: "WBS-58-ST",
    posid: "MGS58-CC4.ST",
    nameFa: "استاتور MGS58",
    projectId: "PRJ-MGS58-CC",
    plannedFinishDay: 74,
    plannedCostIrr: 310_000_000_000,
    actualCostIrr: 122_000_000_000,
    provenance: sap("PRPS/MGS58-CC4.ST"),
  },
  {
    id: "WBS-60-ST",
    posid: "MGH60-HY2.ST",
    nameFa: "استاتور آبی MGH60",
    projectId: "PRJ-MGH60",
    plannedFinishDay: 96,
    plannedCostIrr: 380_000_000_000,
    actualCostIrr: 141_000_000_000,
    provenance: sap("PRPS/MGH60-HY2.ST"),
  },
];

export const ORDERS: ProductionOrder[] = [
  {
    id: "ORD-H2-ST",
    aufnr: "10004521",
    materialId: "MAT-CU-BAR",
    materialNameFa: "استاتور کامل MGS72-SH2 واحد ۲",
    projectId: "PRJ-H2-376-U2",
    wbsId: "WBS-H2-STATOR",
    qty: 1,
    plannedFinishDay: 58,
    status: "REL",
    provenance: sap("AFKO/10004521"),
  },
  {
    id: "ORD-H2-BAR",
    aufnr: "10004518",
    materialId: "MAT-CU-BAR",
    materialNameFa: "مجموعه شینه استاتور MGS72",
    projectId: "PRJ-H2-376-U2",
    wbsId: "WBS-H2-STATOR",
    qty: 1,
    plannedFinishDay: 22,
    status: "CNF",
    provenance: sap("AFKO/10004518"),
  },
  {
    id: "ORD-H2-RT",
    aufnr: "10004530",
    materialId: "MAT-H2-SEAL",
    materialNameFa: "روتور MGS72-SH2 واحد ۲",
    projectId: "PRJ-H2-376-U2",
    wbsId: "WBS-H2-ROTOR",
    qty: 1,
    plannedFinishDay: 72,
    status: "REL",
    provenance: sap("AFKO/10004530"),
  },
  {
    id: "ORD-H2-ASM",
    aufnr: "10004541",
    materialId: "MAT-H2-SEAL",
    materialNameFa: "مونتاژ و تست ژنراتور واحد ۲",
    projectId: "PRJ-H2-376-U2",
    wbsId: "WBS-H2-ASM",
    qty: 1,
    plannedFinishDay: 101,
    status: "CRTD",
    provenance: sap("AFKO/10004541"),
  },
  {
    id: "ORD-58-ST",
    aufnr: "10003802",
    materialId: "MAT-CU-BAR",
    materialNameFa: "استاتور MGS58",
    projectId: "PRJ-MGS58-CC",
    wbsId: "WBS-58-ST",
    qty: 1,
    plannedFinishDay: 74,
    status: "REL",
    provenance: sap("AFKO/10003802"),
  },
  {
    id: "ORD-60-ST",
    aufnr: "10003110",
    materialId: "MAT-CU-BAR",
    materialNameFa: "استاتور MGH60",
    projectId: "PRJ-MGH60",
    wbsId: "WBS-60-ST",
    qty: 1,
    plannedFinishDay: 96,
    status: "REL",
    provenance: sap("AFKO/10003110"),
  },
];

/**
 * Day 0 = 2026-09-05 (۱۴۰۵/۰۶/۱۴).
 * VPI-01 failed today during the in-progress H2 stator impregnation.
 */
export const OPERATIONS: Operation[] = [
  {
    id: "OP-H2-STK",
    orderId: "ORD-H2-ST",
    wbsId: "WBS-H2-STATOR",
    projectId: "PRJ-H2-376-U2",
    seq: "0010",
    nameFa: "چیدمان و جوش هسته استاتور",
    nameEn: "Stator core stacking",
    workCenterId: "WC-STK-01",
    plannedStartDay: -40,
    plannedFinishDay: -18,
    actualStartDay: -40,
    remainingWorkDays: 0,
    totalWorkDays: 22,
    status: "confirmed",
    predecessors: [],
    materialIds: ["MAT-STEEL-LAM"],
    sapAufnr: "10004521",
    sapVornr: "0010",
    provenance: sap("AFVC/10004521-0010"),
  },
  {
    id: "OP-H2-BAR",
    orderId: "ORD-H2-BAR",
    wbsId: "WBS-H2-STATOR",
    projectId: "PRJ-H2-376-U2",
    seq: "0020",
    nameFa: "ساخت شینه و عایق میکا",
    nameEn: "Bar manufacturing",
    workCenterId: "WC-BAR-01",
    plannedStartDay: -55,
    plannedFinishDay: -8,
    actualStartDay: -55,
    remainingWorkDays: 0,
    totalWorkDays: 47,
    status: "confirmed",
    predecessors: [],
    materialIds: ["MAT-CU-BAR", "MAT-MICA"],
    sapAufnr: "10004518",
    sapVornr: "0020",
    provenance: sap("AFVC/10004518-0020"),
  },
  {
    id: "OP-H2-WIN",
    orderId: "ORD-H2-ST",
    wbsId: "WBS-H2-STATOR",
    projectId: "PRJ-H2-376-U2",
    seq: "0030",
    nameFa: "جاگذاری شینه در شیار استاتور",
    nameEn: "Bar insertion",
    workCenterId: "WC-WIN-01",
    plannedStartDay: -16,
    plannedFinishDay: -2,
    actualStartDay: -16,
    remainingWorkDays: 0,
    totalWorkDays: 14,
    status: "confirmed",
    predecessors: ["OP-H2-STK", "OP-H2-BAR"],
    materialIds: ["MAT-CU-BAR"],
    sapAufnr: "10004521",
    sapVornr: "0030",
    provenance: sap("AFVC/10004521-0030"),
  },
  {
    id: "OP-H2-VPI",
    orderId: "ORD-H2-ST",
    wbsId: "WBS-H2-STATOR",
    projectId: "PRJ-H2-376-U2",
    seq: "0040",
    nameFa: "اشباع خلاء-فشار استاتور (VPI)",
    nameEn: "Stator VPI",
    workCenterId: "WC-VPI-01",
    plannedStartDay: -3,
    plannedFinishDay: 7,
    actualStartDay: -3,
    remainingWorkDays: 7,
    totalWorkDays: 10,
    status: "in_progress",
    predecessors: ["OP-H2-WIN"],
    materialIds: ["MAT-RESIN-VPI"],
    sapAufnr: "10004521",
    sapVornr: "0040",
    provenance: sap("AFVC/10004521-0040"),
  },
  {
    id: "OP-H2-CUR",
    orderId: "ORD-H2-ST",
    wbsId: "WBS-H2-STATOR",
    projectId: "PRJ-H2-376-U2",
    seq: "0050",
    nameFa: "پخت رزین استاتور",
    nameEn: "Stator cure",
    workCenterId: "WC-CUR-01",
    plannedStartDay: 7,
    plannedFinishDay: 12,
    remainingWorkDays: 5,
    totalWorkDays: 5,
    status: "released",
    predecessors: ["OP-H2-VPI"],
    materialIds: [],
    sapAufnr: "10004521",
    sapVornr: "0050",
    provenance: sap("AFVC/10004521-0050"),
  },
  {
    id: "OP-H2-ROT",
    orderId: "ORD-H2-RT",
    wbsId: "WBS-H2-ROTOR",
    projectId: "PRJ-H2-376-U2",
    seq: "0060",
    nameFa: "تراش و ماشین‌کاری روتور",
    nameEn: "Rotor turning",
    workCenterId: "WC-ROT-01",
    plannedStartDay: -10,
    plannedFinishDay: 24,
    actualStartDay: -10,
    remainingWorkDays: 24,
    totalWorkDays: 34,
    status: "in_progress",
    predecessors: [],
    materialIds: [],
    sapAufnr: "10004530",
    sapVornr: "0060",
    provenance: sap("AFVC/10004530-0060"),
  },
  {
    id: "OP-H2-BAL",
    orderId: "ORD-H2-RT",
    wbsId: "WBS-H2-ROTOR",
    projectId: "PRJ-H2-376-U2",
    seq: "0070",
    nameFa: "بالانس روتور",
    nameEn: "Rotor balance",
    workCenterId: "WC-BAL-01",
    plannedStartDay: 26,
    plannedFinishDay: 32,
    remainingWorkDays: 6,
    totalWorkDays: 6,
    status: "planned",
    predecessors: ["OP-H2-ROT"],
    materialIds: [],
    sapAufnr: "10004530",
    sapVornr: "0070",
    provenance: sap("AFVC/10004530-0070"),
  },
  {
    id: "OP-H2-ASM",
    orderId: "ORD-H2-ASM",
    wbsId: "WBS-H2-ASM",
    projectId: "PRJ-H2-376-U2",
    seq: "0080",
    nameFa: "مونتاژ استاتور و روتور",
    nameEn: "Assembly",
    workCenterId: "WC-ASM-01",
    plannedStartDay: 58,
    plannedFinishDay: 78,
    remainingWorkDays: 20,
    totalWorkDays: 20,
    status: "planned",
    predecessors: ["OP-H2-CUR", "OP-H2-BAL"],
    materialIds: ["MAT-H2-SEAL"],
    sapAufnr: "10004541",
    sapVornr: "0080",
    provenance: sap("AFVC/10004541-0080"),
  },
  {
    id: "OP-H2-TST",
    orderId: "ORD-H2-ASM",
    wbsId: "WBS-H2-ASM",
    projectId: "PRJ-H2-376-U2",
    seq: "0090",
    nameFa: "تست الکتریکی و نشتی هیدروژن",
    nameEn: "FAT / H2 leak test",
    workCenterId: "WC-TST-01",
    plannedStartDay: 78,
    plannedFinishDay: 96,
    remainingWorkDays: 18,
    totalWorkDays: 18,
    status: "planned",
    predecessors: ["OP-H2-ASM"],
    materialIds: ["MAT-H2-SEAL"],
    sapAufnr: "10004541",
    sapVornr: "0090",
    provenance: sap("AFVC/10004541-0090"),
  },
  {
    id: "OP-H2-BAR-VPI",
    orderId: "ORD-H2-BAR",
    wbsId: "WBS-H2-STATOR",
    projectId: "PRJ-H2-376-U2",
    seq: "0045",
    nameFa: "VPI شینه‌های یدکی واحد ۲",
    nameEn: "Spare bar VPI",
    workCenterId: "WC-VPI-01",
    plannedStartDay: 8,
    plannedFinishDay: 12,
    remainingWorkDays: 4,
    totalWorkDays: 4,
    status: "released",
    predecessors: ["OP-H2-BAR"],
    materialIds: ["MAT-RESIN-VPI"],
    sapAufnr: "10004518",
    sapVornr: "0045",
    provenance: sap("AFVC/10004518-0045"),
  },
  {
    id: "OP-58-WIN",
    orderId: "ORD-58-ST",
    wbsId: "WBS-58-ST",
    projectId: "PRJ-MGS58-CC",
    seq: "0030",
    nameFa: "جاگذاری شینه MGS58",
    nameEn: "MGS58 insertion",
    workCenterId: "WC-WIN-01",
    plannedStartDay: 4,
    plannedFinishDay: 18,
    remainingWorkDays: 14,
    totalWorkDays: 14,
    status: "released",
    predecessors: [],
    materialIds: ["MAT-CU-BAR"],
    sapAufnr: "10003802",
    sapVornr: "0030",
    provenance: sap("AFVC/10003802-0030"),
  },
  {
    id: "OP-58-VPI",
    orderId: "ORD-58-ST",
    wbsId: "WBS-58-ST",
    projectId: "PRJ-MGS58-CC",
    seq: "0040",
    nameFa: "VPI استاتور MGS58",
    nameEn: "MGS58 VPI",
    workCenterId: "WC-VPI-01",
    plannedStartDay: 20,
    plannedFinishDay: 28,
    remainingWorkDays: 8,
    totalWorkDays: 8,
    status: "planned",
    predecessors: ["OP-58-WIN"],
    materialIds: ["MAT-RESIN-VPI"],
    sapAufnr: "10003802",
    sapVornr: "0040",
    provenance: sap("AFVC/10003802-0040"),
  },
  {
    id: "OP-58-CUR",
    orderId: "ORD-58-ST",
    wbsId: "WBS-58-ST",
    projectId: "PRJ-MGS58-CC",
    seq: "0050",
    nameFa: "پخت استاتور MGS58",
    nameEn: "MGS58 cure",
    workCenterId: "WC-CUR-01",
    plannedStartDay: 28,
    plannedFinishDay: 33,
    remainingWorkDays: 5,
    totalWorkDays: 5,
    status: "planned",
    predecessors: ["OP-58-VPI"],
    materialIds: [],
    sapAufnr: "10003802",
    sapVornr: "0050",
    provenance: sap("AFVC/10003802-0050"),
  },
  {
    id: "OP-60-VPI",
    orderId: "ORD-60-ST",
    wbsId: "WBS-60-ST",
    projectId: "PRJ-MGH60",
    seq: "0040",
    nameFa: "VPI استاتور آبی MGH60",
    nameEn: "MGH60 VPI",
    workCenterId: "WC-VPI-01",
    plannedStartDay: 36,
    plannedFinishDay: 46,
    remainingWorkDays: 10,
    totalWorkDays: 10,
    status: "planned",
    predecessors: [],
    materialIds: ["MAT-RESIN-VPI"],
    sapAufnr: "10003110",
    sapVornr: "0040",
    provenance: sap("AFVC/10003110-0040"),
  },
  {
    id: "OP-60-CUR",
    orderId: "ORD-60-ST",
    wbsId: "WBS-60-ST",
    projectId: "PRJ-MGH60",
    seq: "0050",
    nameFa: "پخت استاتور آبی",
    nameEn: "MGH60 cure",
    workCenterId: "WC-CUR-01",
    plannedStartDay: 46,
    plannedFinishDay: 52,
    remainingWorkDays: 6,
    totalWorkDays: 6,
    status: "planned",
    predecessors: ["OP-60-VPI"],
    materialIds: [],
    sapAufnr: "10003110",
    sapVornr: "0050",
    provenance: sap("AFVC/10003110-0050"),
  },
];

export const MILESTONES: Milestone[] = [
  {
    id: "MS-H2-FAT",
    nameFa: "FAT ژنراتور واحد ۲",
    projectId: "PRJ-H2-376-U2",
    wbsId: "WBS-H2-ASM",
    dueDay: 96,
    type: "fat",
    invoicePct: 0.2,
    provenance: sap("MLST/H2-FAT"),
  },
  {
    id: "MS-H2-DLV",
    nameFa: "تحویل در محل نیروگاه",
    projectId: "PRJ-H2-376-U2",
    wbsId: "WBS-H2-ASM",
    dueDay: 106,
    type: "delivery",
    invoicePct: 0.1,
    provenance: sap("MLST/H2-DLV"),
  },
  {
    id: "MS-58-FAT",
    nameFa: "FAT ژنراتور MGS58",
    projectId: "PRJ-MGS58-CC",
    wbsId: "WBS-58-ST",
    dueDay: 118,
    type: "fat",
    invoicePct: 0.25,
    provenance: sap("MLST/58-FAT"),
  },
  {
    id: "MS-60-FAT",
    nameFa: "FAT ژنراتور آبی MGH60",
    projectId: "PRJ-MGH60",
    wbsId: "WBS-60-ST",
    dueDay: 150,
    type: "fat",
    invoicePct: 0.2,
    provenance: sap("MLST/60-FAT"),
  },
];

export const COMMITMENTS: Commitment[] = [
  {
    id: "CM-H2-DLV",
    kind: "customer_delivery",
    hardness: "hard",
    nameFa: "تحویل قراردادی MGS72-SH2 واحد ۲",
    owner: "مدیر پروژه H2-376",
    dueDay: 106,
    priority: 1,
    financialImpactIrr: 2_850_000_000_000,
    penaltyIrrPerDay: 4_275_000_000,
    flexibilityDays: 0,
    criticality: 1,
    status: "on_track",
    projectId: "PRJ-H2-376-U2",
    milestoneId: "MS-H2-DLV",
    provenance: sap("SD-contract / PS milestone"),
  },
  {
    id: "CM-H2-FAT-INV",
    kind: "contract_milestone",
    hardness: "financial",
    nameFa: "صورت‌وضعیت ۲۰٪ پس از FAT",
    owner: "امور قراردادها",
    dueDay: 96,
    priority: 2,
    financialImpactIrr: 570_000_000_000,
    penaltyIrrPerDay: 0,
    flexibilityDays: 7,
    criticality: 0.85,
    status: "on_track",
    projectId: "PRJ-H2-376-U2",
    milestoneId: "MS-H2-FAT",
    provenance: assumed("نقطه صورت‌وضعیت از قرارداد — اعتبارسنجی با SD/PS"),
  },
  {
    id: "CM-H2-STRAT",
    kind: "strategic",
    hardness: "strategic",
    nameFa: "تعهد راهبردی کلاس F هیدروژن‌خنک — دومین واحد سری",
    owner: "مدیرعامل پارس",
    dueDay: 106,
    priority: 1,
    financialImpactIrr: 0,
    penaltyIrrPerDay: 0,
    flexibilityDays: 5,
    criticality: 0.95,
    status: "on_track",
    projectId: "PRJ-H2-376-U2",
    provenance: assumed("تعهد پرتفوی گروه مپنا"),
  },
  {
    id: "CM-58-DLV",
    kind: "customer_delivery",
    hardness: "contractual",
    nameFa: "تحویل MGS58",
    owner: "مدیر پروژه MGS58",
    dueDay: 140,
    priority: 3,
    financialImpactIrr: 1_420_000_000_000,
    penaltyIrrPerDay: 1_420_000_000,
    flexibilityDays: 10,
    criticality: 0.55,
    status: "on_track",
    projectId: "PRJ-MGS58-CC",
    milestoneId: "MS-58-FAT",
    provenance: sap("SD-contract"),
  },
  {
    id: "CM-PAYROLL",
    kind: "payroll",
    hardness: "hard",
    nameFa: "پرداخت حقوق شهریور کارخانه",
    owner: "منابع انسانی / خزانه",
    dueDay: 16,
    priority: 1,
    financialImpactIrr: 186_000_000_000,
    penaltyIrrPerDay: 0,
    flexibilityDays: 2,
    criticality: 0.9,
    status: "on_track",
    provenance: assumed("تعهد حقوق — منبع غیر SAP در MVP"),
  },
  {
    id: "CM-RESIN-PO",
    kind: "supplier_payment",
    hardness: "financial",
    nameFa: "پرداخت PO رزین واسطه",
    owner: "تدارکات",
    dueDay: 22,
    priority: 2,
    financialImpactIrr: 38_000_000_000,
    penaltyIrrPerDay: 0,
    flexibilityDays: 5,
    criticality: 0.6,
    status: "on_track",
    provenance: sap("EKKO/PO-resin"),
  },
];

export const CASH_EVENTS: CashEvent[] = [
  {
    id: "CASH-OPEN",
    kind: "inflow",
    nameFa: "موجودی افتتاحیه نقد عملیاتی",
    amountIrr: 412_000_000_000,
    plannedDay: 0,
    probability: 1,
    fxLinked: false,
    provenance: assumed("خزانه — VALIDATION REQUIRED"),
  },
  {
    id: "CASH-H2-FAT",
    kind: "inflow",
    nameFa: "وصول صورت‌وضعیت FAT واحد ۲",
    amountIrr: 570_000_000_000,
    plannedDay: 186,
    probability: 0.82,
    commitmentId: "CM-H2-FAT-INV",
    projectId: "PRJ-H2-376-U2",
    fxLinked: false,
    provenance: assumed("invoice day 96 + 90d collection lag"),
  },
  {
    id: "CASH-PAYROLL",
    kind: "outflow",
    nameFa: "حقوق شهریور",
    amountIrr: 186_000_000_000,
    plannedDay: 16,
    probability: 1,
    commitmentId: "CM-PAYROLL",
    fxLinked: false,
    provenance: assumed("payroll"),
  },
  {
    id: "CASH-RESIN",
    kind: "outflow",
    nameFa: "پرداخت رزین",
    amountIrr: 38_000_000_000,
    plannedDay: 22,
    probability: 1,
    commitmentId: "CM-RESIN-PO",
    fxLinked: true,
    provenance: sap("F110 proposal synthetic"),
  },
  {
    id: "CASH-ENERGY",
    kind: "outflow",
    nameFa: "بهای انرژی کارخانه (ماهانه)",
    amountIrr: 24_000_000_000,
    plannedDay: 20,
    probability: 1,
    fxLinked: false,
    provenance: assumed("utility"),
  },
  {
    id: "CASH-58-INV",
    kind: "inflow",
    nameFa: "وصول FAT پروژه MGS58",
    amountIrr: 355_000_000_000,
    plannedDay: 193,
    probability: 0.8,
    projectId: "PRJ-MGS58-CC",
    fxLinked: false,
    provenance: assumed("MGS58 invoice + lag"),
  },
];

export const OPENING_CASH_IRR = 412_000_000_000;

export const GOLDEN_DISRUPTION = {
  id: "DIS-VPI-01-20D",
  resourceId: "WC-VPI-01",
  nameFa: "ازکارافتادگی مخزن VPI-01 به‌مدت ۲۰ روز",
  startDay: 0,
  durationDays: 20,
  causeFa:
    "قفل مکانیکی پمپ خلاء هنگام سیکل استاتور MGS72-SH2 واحد ۲. قطعه یدکی وارداتی است.",
  iranFactors: ["sanctions", "import", "fx", "energy"],
};

export const COMPANY = {
  id: "MAPNA-PARS",
  nameFa: "شرکت مهندسی و ساخت ژنراتور مپنا (پارس)",
  nameEn: "MAPNA Generator Engineering and Manufacturing Co. (PARS)",
  factSources: [
    {
      title: "MAPNA Group — Pars company page",
      url: "https://mapnagroup.com/mapnacompanies/mapna-pars/?lang=en",
      retrieved: "2026-09-05",
    },
    {
      title: "mapnagenerator.com — overview",
      url: "https://mapnagenerator.com/En/Overview",
      retrieved: "2026-09-05",
    },
    {
      title: "MAPNA Pars unveils first 376 MW hydrogen-cooled generator",
      url: "https://mapnagroup.com/48334/mapna-pars-unveils-first-376-mw-hydrogen-cooled-generator-unit/?lang=en",
      retrieved: "2026-09-05",
    },
  ],
};
