/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlueprintRouteImport } from './routes/blueprint'
import { Route as CashRouteImport } from './routes/cash'
import { Route as DecisionRouteImport } from './routes/decision'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ScenarioRouteImport } from './routes/scenario'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ResourcesIdRouteImport } from './routes/resources.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintRoute = BlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoute = DecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioRoute = ScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const ResourcesIdRoute = ResourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blueprint': typeof BlueprintRoute
  '/cash': typeof CashRoute
  '/decision': typeof DecisionRoute
  '/graph': typeof GraphRoute
  '/history': typeof HistoryRoute
  '/impact': typeof ImpactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/scenario': typeof ScenarioRoute
  '/simulation': typeof SimulationRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/resources/$id': typeof ResourcesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blueprint': typeof BlueprintRoute
  '/cash': typeof CashRoute
  '/decision': typeof DecisionRoute
  '/graph': typeof GraphRoute
  '/history': typeof HistoryRoute
  '/impact': typeof ImpactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/scenario': typeof ScenarioRoute
  '/simulation': typeof SimulationRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/resources/$id': typeof ResourcesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blueprint': typeof BlueprintRoute
  '/cash': typeof CashRoute
  '/decision': typeof DecisionRoute
  '/graph': typeof GraphRoute
  '/history': typeof HistoryRoute
  '/impact': typeof ImpactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/scenario': typeof ScenarioRoute
  '/simulation': typeof SimulationRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/resources/$id': typeof ResourcesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blueprint'
    | '/cash'
    | '/decision'
    | '/graph'
    | '/history'
    | '/impact'
    | '/projects'
    | '/resources'
    | '/scenario'
    | '/simulation'
    | '/projects/$id'
    | '/resources/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blueprint'
    | '/cash'
    | '/decision'
    | '/graph'
    | '/history'
    | '/impact'
    | '/projects'
    | '/resources'
    | '/scenario'
    | '/simulation'
    | '/projects/$id'
    | '/resources/$id'
  id:
    | '__root__'
    | '/'
    | '/blueprint'
    | '/cash'
    | '/decision'
    | '/graph'
    | '/history'
    | '/impact'
    | '/projects'
    | '/resources'
    | '/scenario'
    | '/simulation'
    | '/projects/$id'
    | '/resources/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlueprintRoute: typeof BlueprintRoute
  CashRoute: typeof CashRoute
  DecisionRoute: typeof DecisionRoute
  GraphRoute: typeof GraphRoute
  HistoryRoute: typeof HistoryRoute
  ImpactRoute: typeof ImpactRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ScenarioRoute: typeof ScenarioRoute
  SimulationRoute: typeof SimulationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint': {
      id: '/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof BlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision': {
      id: '/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof DecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario': {
      id: '/scenario'
      path: '/scenario'
      fullPath: '/scenario'
      preLoaderRoute: typeof ScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/resources/$id': {
      id: '/resources/$id'
      path: '/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof ResourcesIdRouteImport
      parentRoute: typeof ResourcesRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesIdRoute: typeof ResourcesIdRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesIdRoute: ResourcesIdRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlueprintRoute: BlueprintRoute,
  CashRoute: CashRoute,
  DecisionRoute: DecisionRoute,
  GraphRoute: GraphRoute,
  HistoryRoute: HistoryRoute,
  ImpactRoute: ImpactRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ResourcesRoute: ResourcesRouteWithChildren,
  ScenarioRoute: ScenarioRoute,
  SimulationRoute: SimulationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
